apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "letsencrypt-cde-mapper"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: filippo@metacell.us
    privateKeySecretRef:
      name: letsencrypt-cde-mapper
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-cde-mapper
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: cde-mapper-ingress
spec:
  rules:
  - host: "{{DOMAIN}}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cde-mapper
            port:
              number: 80
  tls:
  - hosts:
    - {{DOMAIN}}
    secretName: cde-mapper-tls
