name: CI for PRs

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TSX: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: (.*\.ts$|.*\.tsx$)

